version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: bunny
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=bunny
      - POSTGRES_PASSWORD=mn3dfs4so33dfs2j
      - POSTGRES_DB=bounce
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  rabbitmq-data:
  postgres-data:
